# Generated by Django 4.2.2 on 2023-07-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('development', 'permiso como desarrollador'), ('scrum_master', 'permiso como scrum_master'), ('product_owner', 'permiso como product_owner')]},
        ),
    ]
