# Generated by Django 4.2.2 on 2023-07-07 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('development', 'permiso como desarrollador'), ('scrum_master', 'permiso como scrum_master'), ('product_owner', 'permiso como product_owner')], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 20, 33, 4, 589783)),
        ),
        migrations.AddField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 20, 33, 4, 589783)),
        ),
    ]
